### ISSUE TITLE
Adding Django 3.2 support

### ISSUE THREAD

**Issue by Tecktron** [jacobian/django-postgres-unlimited-varchar#2]
First off thanks for this very useful field, I use it a ton. Recently I updating a project to Django 3.2 and noticed that it was causing an error. After a quick rummage around, I found the issue to the new `db_collation` field now being a requirement of the  `CharField`, so I added support for it with a default  value of `None`. I created a simple PR to fix it, which also shouldn't effect previous versions.
https://github.com/jacobian/django-postgres-unlimited-varchar/pull/1

Thanks

**Comment by jacobian** [comment]
Fixed, thanks for the PR!
